config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :categories, only: :show

  get :play_random, to: "titles#random"

  resource :search, only: :new

  resources :titles do
    resources :tweaks do
      resources :descriptions do
        put :upvote
      end
    end
  end

  resources :descriptions, only: :index

  resources :daily_wit_stops

  resources :users do
    resources :descriptions, only: :index, controller: 'users/descriptions'
    resource :email_preferences
  end

  resources :likes


  namespace :public do
    get 'email_preferences/:id', to: 'email_preferences#update', as: 'email_preferences'
  end


  get :privacy_policy, controller: 'static_pages'
  get :terms_of_use, controller: 'static_pages'

end

app/models/tweak.rb
class Tweak < ApplicationRecord
  belongs_to :title
  belongs_to :user
  has_many :descriptions, dependent: :destroy

  validates_uniqueness_of :name
end

app/controllers/tweaks_controller.rb
class TweaksController < ApplicationController

  def create
    store_location_and_params
    redirect_to new_user_session_path and return unless user_signed_in?

    service = TweakCreateService.new(params, current_user).perform

    @title = service.title
    @tweak = service.tweak
    @description = service.description
    @descriptions = service.descriptions

    @create = true
    render :show
  end

  def show
    @title = Title.find(params[:title_id])
    @tweak = @title.tweaks.find(params[:id])
    @descriptions = @tweak.descriptions.includes(:user, :likes).order(likes_count: :desc, created_at: :desc)
  end

  private
    def store_location_and_params
      session[:tweak_params] = params unless user_signed_in?
    end
end

app/views/tweaks/_show.html.haml
%h1
  "#{tweak.name}"

%ul.list-group
  - @descriptions.each do |description|
    %li.list-group-item
      .btn-group.btn-group
        - if description.liked_by?(current_user)
          %button.btn.btn-disabled.btn-sm{:type => "button"}
            = description.likes_count
            %i.fa.fa-thumbs-up
        - else
          = link_to title_tweak_description_upvote_path(@title, tweak, description), remote: true, method: :put do
            %button.btn.btn-success.btn-sm{:type => "button"}
              = description.likes_count
              %i.fa.fa-thumbs-up
      %h4{id: dom_id(description)}
        = link_to title_tweak_description_path(@title, tweak, description) do
          = description.text

        -if description.user == current_user
          = link_to edit_title_tweak_description_path(@title, @tweak, description), remote: true do
            %i.fa.fa-pencil


      \- #{description.user.username}


.form-group
  %button.btn.btn-default{"aria-controls" => "collapseExample", "aria-expanded" => "false", "data-target" => "#collapseExample", "data-toggle" => "collapse", :type => "button"}
    Add your own description

  #collapseExample.collapse.m1t
    .card.card-block
      = form_for :description, url: title_tweak_descriptions_path(@title, tweak), remote: true, method: :post do |f|
        .row.form-group
          .col-md-6
            = f.text_area :text, value: nil, placeholder: "Add your description of '#{tweak.name}'", rows: 3, class: 'form-control'
        .row
          .col-md-8
            = f.submit 'Save', class: 'btn btn-primary'

app/views/tweaks/show.html.haml
=link_to "< Back to #{@title.name}", title_path(@title)

%div{id: dom_id(@tweak)}
  = render partial: 'show', locals: {tweak: @tweak}

- if @create
  //we just came from the create action, we should do the sound
  :javascript
    var create_sound = new Audio('/sounds/description_create.mp3');
    create_sound.play();