config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :categories, only: :show

  get :play_random, to: "titles#random"

  resource :search, only: :new

  resources :titles do
    resources :tweaks do
      resources :descriptions do
        put :upvote
      end
    end
  end

  resources :descriptions, only: :index

  resources :daily_wit_stops

  resources :users do
    resources :descriptions, only: :index, controller: 'users/descriptions'
    resource :email_preferences
  end

  resources :likes


  namespace :public do
    get 'email_preferences/:id', to: 'email_preferences#update', as: 'email_preferences'
  end


  get :privacy_policy, controller: 'static_pages'
  get :terms_of_use, controller: 'static_pages'

end

app/models/daily_wit_stop.rb
class DailyWitStop < ApplicationRecord
  
  belongs_to :description
  belongs_to :user

  scope :scheduled, -> { where(sent: false) }
  scope :sent, -> { where(sent: true) }

  validate :only_one_per_day, on: :create


  private
    def only_one_per_day
      wit_stops = DailyWitStop.scheduled.any?
      if wit_stops
        errors.add(:created_at, "Cannot schedule more than 1 per day")
      end
    end
end

app/controllers/daily_wit_stops_controller.rb
class DailyWitStopsController < ApplicationController
  http_basic_authenticate_with name: "letterloose", password: "nougatcenter"
  before_action :authenticate_user!

  before_action :fetch_descriptions, except: [:create, :destroy]
  before_action :fetch_wit_stops, except: [:create, :destroy]
  
  def index
    
  end

  def create
    @daily_wit_stop = DailyWitStop.create(user: current_user, description_id: params[:description_id])
    if @daily_wit_stop.valid? 
      redirect_to daily_wit_stops_path
    else
      redirect_to daily_wit_stops_path, flash: { error: @daily_wit_stop.errors.full_messages }
    end
  end

  def new
    @preview_description = Description.includes(:user, :likes, tweak: :title).find(params[:description_id])
  end


  def destroy
    @daily_wit_stop = DailyWitStop.find(params[:id])
    @daily_wit_stop.destroy
    redirect_to daily_wit_stops_path
  end

  private
    def fetch_wit_stops
      @daily_wit_stops = DailyWitStop.includes(:user, description: [:user, :likes, tweak: :title])
    end

    def fetch_descriptions
      @page = params[:page]
      @descriptions = descriptions.page(@page).per(25)
    end

    def descriptions
      Description
        .order(created_at: :desc)
        .includes(:user, :likes, tweak: :title)
    end
end

app/views/daily_wit_stops/_email_preview.html.haml
%div.pattern-background
  = image_tag 'title.png', style: 'max-width:720px;width: 80%;margin: auto;display: block; position: relative'
  .row
    .col-md-8.col-md-offset-2
      .text-center
        %h2.m00y.text-white Daily Wit Stop
      .panel.m3y
        .panel-body
          %div
            %p
              %h4
                = description.present? ? description.tweak.title.name : 'PLACEHOLDER'

            %h5{margin: '0px'}
              - if description.present?
                %div= link_to description.tweak.name, title_tweak_path(description.tweak.title, description.tweak)

            = description.present? ? "\"#{description.text}\"": 'Click "show preview" to add content'

            - if description.present?
              = description.likes_count
              %i.fa.fa-thumbs-up
            

              %br
              %small.small.text-muted
                = link_to description.user.username, user_descriptions_path(description.user)
                = "- #{time_ago_in_words(description.created_at)} ago"
              %br

  %p.text-white.text-center
    To unsubscribe from the Daily Wit Stop 'click here'

app/views/daily_wit_stops/_index.html.haml
.row
  .col-md-4
    - @descriptions.each do |description|
      = render partial: 'shared/description', locals: {description: description}
      .clearfix
        = link_to 'Show preview', new_daily_wit_stop_path(description_id: description.id), class: 'btn btn-default btn-sm pull-right'
      %hr
    = paginate(@descriptions)
  .col-md-8
    = render partial: 'email_preview', locals: {description: @preview_description}

    - if @preview_description.present?
      = link_to daily_wit_stops_path(description_id: @preview_description.id), method: :post, class: 'btn btn-primary btn-lg' do
        Looks good! Schedule to Send

      = link_to daily_wit_stops_path, class: 'btn btn-default pull-right' do
        Reset
      %hr

    %h3 Scheduled
    - if @daily_wit_stops.scheduled.any?
      - @daily_wit_stops.scheduled.each do |daily_wit_stop|
        .col-md-6.panel.panel-default
          = render partial: 'shared/description', locals: {description: daily_wit_stop.description}
          %hr
        .col-md-6
          .alert.alert-info.alert-sm
            Scheduled to send at 3pm PST #{Date.today}
          .alert.alert-warning.alert-sm
            Generated by: #{daily_wit_stop.user.username}
          .alert.alert-danger.alert-sm

            = link_to daily_wit_stop_path(daily_wit_stop), method: :delete do
              %i.fa.fa-trash
              Unschedule
    .row
      .col-xs-12
        %hr
        %h3 Sent
    .row.row-flex.row-flex-wrap
      - @daily_wit_stops.sent.each do |daily_wit_stop|
        .col-md-6
          %div
            = render partial: 'shared/description', locals: {description: daily_wit_stop.description}
            = "#{daily_wit_stop.sent_at.strftime("%a, %e %b %Y %H:%M:%S %z")} BY: #{daily_wit_stop.user.username}"
            %hr

app/views/daily_wit_stops/index.html.haml
= render 'index'

app/views/daily_wit_stops/new.html.haml
= render 'index'