config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :categories, only: :show

  get :play_random, to: "titles#random"

  resource :search, only: :new

  resources :titles do
    resources :tweaks do
      resources :descriptions do
        put :upvote
      end
    end
  end

  resources :descriptions, only: :index

  resources :daily_wit_stops

  resources :users do
    resources :descriptions, only: :index, controller: 'users/descriptions'
    resource :email_preferences
  end

  resources :likes


  namespace :public do
    get 'email_preferences/:id', to: 'email_preferences#update', as: 'email_preferences'
  end


  get :privacy_policy, controller: 'static_pages'
  get :terms_of_use, controller: 'static_pages'

end

app/views/shared/_description.html.haml
%div
  %p
    %h4
      = description.tweak.title.name
      .pull-right
        = link_to '#', onclick: "postToFeed('#{title_tweak_description_path(description.tweak.title, description.tweak, description)}');" do
          %i.fa.fa-facebook-official

  %h5{margin: '0px'}
    %div= link_to description.tweak.name, title_tweak_path(description.tweak.title, description.tweak)

  = "\"#{description.text}\""

  - if description.liked_by?(current_user)
    = description.likes_count
    %i.fa.fa-thumbs-up
  - else
    = link_to title_tweak_description_upvote_path(description.tweak.title, description.tweak, description, source: 'index'), remote: true, method: :put do
      = description.likes_count
      %i.fa.fa-thumbs-up

  %br
  %small.small.text-muted
    = link_to description.user.username, user_descriptions_path(description.user)
    = "- #{time_ago_in_words(description.created_at)} ago"
  %br

app/views/shared/_google_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-103502600-1', 'auto');
  ga('send', 'pageview');

app/views/shared/_how_to_play.html.haml
.row
  .col-md-12
    %h1
      LetterLoose is a game for people who like words, wit, and laughter.
    %p
      Alter a film, book, or song title, or a common phrase, by adding, subtracting, or changing one letter.

      %a.font20.pull-right{"data-toggle" => "modal", :href => "#howToPlay"} 
        How to play.
        %i.fa.fa-info-circle
  .col-md-12
    #howToPlay.modal.fade
      .modal-dialog.modal-lg
        .modal-content
          .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
            %h4.modal-title How To Play
          .modal-body
            %p
              The premise of the game is that you alter a film, book, or song title, or a common phrase, by adding, subtracting, or changing
              %strong ONE
              letter.  Now you've created a new title or phrase. The challenge is to construct a clever description for what you've just created.
            %hr
            .row
              .col-md-4
                .highest-rated-container.pad2.panel.panel-default
                  %strong Add-a-letter example:
                  %ol
                    %li Baker's Dozen
                    %li Add an "R"
                    %li
                      = "Ba<strong>R</strong>ker's Dozen".html_safe
                  %strong New Description:
                  %br
                  A litter of 13 puppies

              .col-md-4
                .weeks-highest-rated.pad2.panel.panel-default
                  %strong Delete-a-letter example:
                  %ol
                    %li Big Lebowski.
                    %li Delete the 'g'.
                    %li Bi Lebowski.
                  %strong New Description:
                  %br
                  Polish immigrant struggles with his sexuality
              .col-md-4
                .pad2.panel.panel-default
                  %strong Change-a-letter example:
                  %ol
                    %li Lust for Life
                    %li Change first "L" to a "D"
                    %li= "<strong>D</strong>ust for Life".html_safe
                  %strong New Description:
                  %br
                  Roomba Guarantee

          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close