config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :categories, only: :show

  get :play_random, to: "titles#random"

  resource :search, only: :new

  resources :titles do
    resources :tweaks do
      resources :descriptions do
        put :upvote
      end
    end
  end

  resources :descriptions, only: :index

  resources :daily_wit_stops

  resources :users do
    resources :descriptions, only: :index, controller: 'users/descriptions'
    resource :email_preferences
  end

  resources :likes


  namespace :public do
    get 'email_preferences/:id', to: 'email_preferences#update', as: 'email_preferences'
  end


  get :privacy_policy, controller: 'static_pages'
  get :terms_of_use, controller: 'static_pages'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :titles, dependent: :destroy

  rails_admin do
    exclude_fields :titles
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all

    @highest_rated_descriptions_all_time = descriptions.limit(25)
    @current_weeks_highest_rated_descriptions = descriptions.where("created_at > ?", 7.days.ago).limit(25)
    @most_recent_descriptions = descriptions.reorder(created_at: :desc).limit(25)

    @top_users = TopUserService.new.perform
  end

  def show
    @category = Category.find(params[:id])
    @titles = @category.titles.order(name: :asc).page(params[:page]).per(1500)
  end

  private
    def descriptions
      Description
        .includes(:user, :likes, tweak: :title)
        .order(likes_count: :desc)
    end
end

app/views/categories/index.html.haml
= render 'shared/how_to_play'

.row
  .col-md-12
    %h3
      Play by clicking on a category

  - @categories.each do |category|
    .col-md-2.category-link
      = link_to category.name, play_random_path(category_id: category.id)

  .col-md-2.category-link
    = link_to play_random_path do
      Random Play

.row
  .col-md-12
    .m1t
      %button.btn.btn-default{"aria-controls" => "searchBox", "aria-expanded" => "false", "data-target" => "#searchBox", "data-toggle" => "collapse", :type => "button"}
        or search for a specific title

      #searchBox.collapse
        = render partial: 'titles/search'

%hr
.row
  .col-md-4.col-md-offset-4
    = image_tag "vote_now.png", style: 'max-width: 100%;margin:auto;display:block;'
.row
  .col-md-9
    .row
      .col-md-4
        %h4.text-center
          HIGHEST RATED OF ALL TIME
        .panel.panel-default.highest-rated-container
          .panel-body
            - @highest_rated_descriptions_all_time.each do |description|
              %div{class: dom_id(description)}
                = render partial: 'shared/description', locals: {description: description}
              %hr

      .col-md-4
        %h4.text-center THIS WEEK'S HIGHEST RATED
        .panel.panel-default.weeks-highest-rated
          .panel-body
            - @current_weeks_highest_rated_descriptions.each do |description|
              %div{class: dom_id(description)}
                = render partial: 'shared/description', locals: {description: description}
              %hr

      .col-md-4
        %h4.text-center MOST RECENT
        .panel.panel-default
          .panel-body
            - @most_recent_descriptions.each do |description|
              %div{class: dom_id(description)}
                = render partial: 'shared/description', locals: {description: description}
              %hr
  .col-md-3
    %h4.text-center &#127942; TOP USERS THIS WEEK
    
    %ul.list-group
      - @top_users.each_with_index do |user, i|
        %li.list-group-item{style:"background-color: rgba(228,34,46, #{1.to_f/(i+1)});"}
          = link_to user_descriptions_path(user[:user_id]), style:'color:#000;' do
            - if i == 0
              .text-white
                %h5
                  = "##{i+1}"
                  = user[:username]
                  .pull-right
                    %i.fa.fa-thumbs-up
                    = user[:count]
            - else
              = "#{i+1}"
              = user[:username]
              .pull-right
                %i.fa.fa-thumbs-up
                = user[:count]
          

.row
  .col-md-12
    = link_to "SEE ALL DESCRIPTIONS", descriptions_path, class: 'btn btn-primary btn-block'

%br
%br

%br

app/views/categories/show.html.haml
= link_to '< Back to Start', root_path
%br
%br
.row
  .col-md-6
    = form_for :title, url: titles_path, html: {class: 'form-inline'}, method: :post do |f|
      .form-group
        = f.hidden_field :category_id, value: @category.id
        %label Add your own:
        = f.text_field :name, class: 'form-control', placeholder: 'e.g., Game of Thrones'

      = f.submit 'Save', class: 'btn btn-success btn-sm'


%br
%ul.list-group
  - @titles.in_groups_of(3).each do |grouping|
    %li.list-group-item
      .row
        - [0,1,2].each do |i|
          - if grouping[i].present?
            .col-md-4
              =link_to title_path(grouping[i]) do
                = grouping[i].name

= paginate @titles